import { Box, Button, Flex, Heading, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  // Render Methods
  const renderNotConnectedContainer = () => (
    <Box m="4">
      <Button
        bg="cyan.500"
        _hover={{ bg: "cyan.400" }}
        _focus={{ bg: "cyan.400" }}
      >
        Connect to Wallet
      </Button>
    </Box>
  );

  return (
    <div>
      <Head>
        <title>Astronaut NFT Collection</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" bg="gray.900" minH="100vh" minW="100vw" color="gray.100">
        <Flex
          justifyContent="center"
          alignItems="center"
          minH="100vh"
          flexDir="column"
        >
          <Heading as="h1" color="cyan.400" textAlign="center">
            Astronaut NFT Collection
          </Heading>
          <Text textAlign="center">
            Earn an unique and pretty cool astronaut avatar
          </Text>
          {renderNotConnectedContainer()}
        </Flex>
      </Box>
    </div>
  );
};

export default Home;
